# プラグイン管理
[[plugins]]
repo = 'Shougo/dein.vim'

## ファイラー

[[plugins]]
repo = 'ryanoasis/vim-devicons'

# fernの設定
[[plugins]]
repo = 'lambdalisue/fern.vim'
hook_add = '''
  let g:fern#default_hidden=1
  let g:fern#disable_default_mappings=1
  nnoremap <silent> <Leader>n :Fern . -reveal=% -drawer -toggle -width=30<CR>
  function! FernInit() abort
    set norelativenumber
    set nonumber
    set signcolumn=no
   	nnoremap <buffer><expr>
	    \ <Plug>(fern-my-open-or-expand-or-collapse)
	    \ fern#smart#leaf(
	    \   "<Plug>(fern-action-open)",
	    \   "<Plug>(fern-action-expand)",
	    \   "<Plug>(fern-action-collapse)",
	    \ )
    nnoremap <silent> <buffer> o <Plug>(fern-my-open-or-expand-or-collapse)
    nnoremap <silent> <buffer> <cr> <Plug>(fern-my-open-or-expand-or-collapse)
    nnoremap <silent> <buffer> i <Plug>(fern-action-open:split)
    nnoremap <silent> <buffer> s <Plug>(fern-action-open:vsplit)

    nnoremap <silent> <buffer> <backspace> <Plug>(fern-action-leave)

    nnoremap <silent> <buffer> cp <Plug>(fern-action-clipboard-copy)
    nnoremap <silent> <buffer> mv <Plug>(fern-action-clipboard-move)
    nnoremap <silent> <buffer> pp <Plug>(fern-action-clipboard-paste)
    nnoremap <silent> <buffer> rename <Plug>(fern-action-rename)
    nnoremap <silent> <buffer> del <Plug>(fern-action-remove)
  endfunction
  augroup fern
    autocmd!
    autocmd FileType fern call FernInit()
  augroup END
'''

# fernにgitの差分を表示
[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'
depends = ['lambdalisue/fern.vim']

# fernにpreviewを表示
[[plugins]]
repo = 'yuki-yano/fern-preview.vim'
hook_add = '''
  function! s:fern_settings() abort
    nnoremap <silent> <buffer> <leader>p <Plug>(fern-action-preview:auto:toggle)
    nnoremap <silent> <buffer> l <Plug>(fern-action-preview:scroll:down:half)
    nnoremap <silent> <buffer> h <Plug>(fern-action-preview:scroll:up:half)
    nnoremap <silent> <buffer> <expr> <Plug>(fern-quit-or-close-preview) fern_preview#smart_preview("\<Plug>(fern-action-preview:close)", ":q\<CR>")
    nnoremap <silent> <buffer> q <Plug>(fern-quit-or-close-preview)

  endfunction

  augroup fern-settings
    autocmd!
    autocmd FileType fern call s:fern_settings()
  augroup END
'''
depends = ['lambdalisue/fern.vim']

[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'
hook_add = '''
  let g:fern#renderer = "nerdfont"
  let g:fern#renderer#nerdfont#indent_markers=1
'''
depends = ['lambdalisue/fern.vim']

# fernアイコン表示
[[plugins]]
repo = 'lambdalisue/nerdfont.vim'

# アイコンの配色を変更
[[plugins]]
repo = 'lambdalisue/glyph-palette.vim'
hook_add = '''
  augroup my-glyph-palette
    autocmd! *
    autocmd FileType fern call glyph_palette#apply()
  augroup END
'''

# 文字色変更
[[plugins]]
repo = 'chriskempson/vim-tomorrow-theme'

# 末尾の無駄なスペースをハイライト、削除
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

# j,kの移動速度アップ
[[plugins]]
repo = 'rhysd/accelerated-jk'
hook_add = '''
  nnoremap j <Plug>(accelerated_jk_gj)
  nnoremap k <Plug>(accelerated_jk_gk)
'''

# tomlのsyntax
[[plugins]]
repo = 'cespare/vim-toml'

# タブのサイズ変更
[[plugins]]
repo = "simeji/winresizer"
hook_add = 'nmap <silent> <Leader>e <C-e>'

# vimヘルプの日本語化
[[plugins]]
repo = 'vim-jp/vimdoc-ja'
hook_add = 'set helplang=ja'

# 置換結果のプレビュー
[[plugins]]
repo = 'markonm/traces.vim'

# ヤンク位置をハイライト
[[plugins]]
repo = 'machakann/vim-highlightedyank'

# denops（Deno統合）
[[plugins]]
repo = 'vim-denops/denops.vim'

# チートシート
[[plugins]]
repo = 'reireias/vim-cheatsheet'
hook_add = '''
  let g:cheatsheet#cheat_file = '~/.cheatsheet.md'
  nnoremap <silent> <leader><leader>c :Cheat<CR>
'''
